version: '3.8'

services:
  presence:
    build: .
    container_name: presence
    ports:
      - "3000:3000"
    volumes:
      - ./posts:/usr/src/app/posts
    environment:
      - PORT=3000
      - POSTS_DIR=/usr/src/app/posts
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
